# remember to use tabs instead of spaces in makefiles
# in vscode: on the bottom right side select tab setup for that file
# https://stackoverflow.com/questions/16476196/undefined-reference-to-curl-global-init-curl-easy-init-and-other-functionc

server: client.cpp
	g++ -o client.o client.cpp -lX11 -lcurl
	